import { NextRequest, NextResponse } from 'next/server';
import { enhancedGoogleSheetsService } from '@/lib/googleSheetsEnhanced';
import { GameData, GameFormData, BulkGameData } from '@/lib/types';
import { requireAdminAuth } from '@/lib/apiAuth';
import { KVCacheService } from '@/lib/kv';

// GET /api/games - List all games with optional filters
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    
    // Parse query parameters for filtering
    const filters = {
      playerId: searchParams.get('playerId') || undefined,
      gameType: searchParams.get('gameType') || undefined,
      dateFrom: searchParams.get('dateFrom') || undefined,
      dateTo: searchParams.get('dateTo') || undefined,
      result: searchParams.get('result') || undefined,
      eventId: searchParams.get('eventId') || undefined,
      isVerified: searchParams.get('isVerified') ? searchParams.get('isVerified') === 'true' : undefined,
    };

    // Remove undefined values
    const cleanFilters = Object.fromEntries(
      Object.entries(filters).filter(([_, value]) => value !== undefined)
    );

    const games = await enhancedGoogleSheetsService.getGames(cleanFilters);
    
    return NextResponse.json(games);
  } catch (error) {
    console.error('Games API GET error:', error);
    return NextResponse.json(
      { error: 'Failed to retrieve games' },
      { status: 500 }
    );
  }
}

// POST /api/games - Create a new game
export async function POST(request: NextRequest) {
  try {
    // Check admin authentication
    const authResult = await requireAdminAuth(request);
    if (!authResult.isAdmin) {
      return NextResponse.json(
        { error: authResult.error || 'Admin privileges required' },
        { status: 403 }
      );
    }

    const gameFormData: GameFormData = await request.json();
    
    // Validate required fields
    if (!gameFormData.player1Id || !gameFormData.player2Id || !gameFormData.result) {
      return NextResponse.json(
        { error: 'Missing required fields: player1Id, player2Id, result' },
        { status: 400 }
      );
    }

    if (gameFormData.player1Id === gameFormData.player2Id) {
      return NextResponse.json(
        { error: 'Players must be different' },
        { status: 400 }
      );
    }

    if (!['player1', 'player2', 'draw'].includes(gameFormData.result)) {
      return NextResponse.json(
        { error: 'Invalid result. Must be player1, player2, or draw' },
        { status: 400 }
      );
    }

    // Get player names from members data (source of truth for the frontend)
    console.log('Getting players from members data...');
    let player1 = null;
    let player2 = null;
    
    try {
      // Get all members using the same method as the frontend
      const registrations = await enhancedGoogleSheetsService.getMembersFromParentsAndStudents();
      
      // Add IDs to members data (same logic as /api/members endpoint)
      const members = registrations.map((registration, index) => ({
        ...registration,
        id: registration.rowIndex ? `reg_row_${registration.rowIndex}` : `member_${index + 1}`
      }));
      
      const member1 = members.find(m => m.id === gameFormData.player1Id);
      const member2 = members.find(m => m.id === gameFormData.player2Id);
      
      if (member1) {
        player1 = {
          id: gameFormData.player1Id,
          name: member1.playerName,
          grade: member1.playerGrade,
          wins: 0,
          losses: 0,
          points: 0,
          rank: 999,
          lastActive: member1.timestamp || new Date().toISOString(),
          email: member1.parentEmail || ''
        };
      }
      
      if (member2) {
        player2 = {
          id: gameFormData.player2Id,
          name: member2.playerName,
          grade: member2.playerGrade,
          wins: 0,
          losses: 0,
          points: 0,
          rank: 999,
          lastActive: member2.timestamp || new Date().toISOString(),
          email: member2.parentEmail || ''
        };
      }
    } catch (error) {
      console.error('Error getting players from members data:', error);
    }

    if (!player1 || !player2) {
      return NextResponse.json(
        { error: 'One or both players not found' },
        { status: 404 }
      );
    }

    // Create game data object
    const gameData: GameData = {
      id: '', // Will be generated by addGame
      player1Id: gameFormData.player1Id,
      player1Name: player1.name,
      player2Id: gameFormData.player2Id,
      player2Name: player2.name,
      result: gameFormData.result,
      gameDate: gameFormData.gameDate || new Date().toISOString().split('T')[0],
      gameTime: gameFormData.gameTime || 0,
      gameType: gameFormData.gameType || 'ladder',
      eventId: gameFormData.eventId,
      notes: gameFormData.notes,
      recordedBy: 'admin', // TODO: Get from auth context
      recordedAt: new Date().toISOString(),
      opening: gameFormData.opening,
      endgame: gameFormData.endgame,
      isVerified: false,
    };

    // Add game to Google Sheets (rankings will be calculated dynamically)
    const gameId = await enhancedGoogleSheetsService.addGame(gameData);

    return NextResponse.json(
      { 
        message: 'Game created successfully',
        gameId,
        game: { ...gameData, id: gameId }
      },
      { status: 201 }
    );
  } catch (error) {
    console.error('Games API POST error:', error);
    return NextResponse.json(
      { error: 'Failed to create game' },
      { status: 500 }
    );
  }
}

